name: Deploy CloudCalculator

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Service Account Key
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_PRICING_CALCULATOR_CREDENTIALS }}
        run: |
          echo "$GCP_PRICING_CALCULATOR_CREDENTIALS" > gcp_cloudbilling_service_account_websitelocal.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/gcp_cloudbilling_service_account_websitelocal.json

      - name: Install Dependencies
        run: npm install

      - name: Build and Deploy
        run: npm run build && npm run export
