name: Test GitHub Secrets

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub Actions page

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3

      - name: Load and Validate Secret
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_PRICING_CALCULATOR_CREDENTIALS }}
        run: |
          # Test if the secret is available
          echo "$GCP_SERVICE_ACCOUNT_KEY" | jq .project_id || echo "Secret not loaded correctly"

      - name: Save Secret to File (Test)
        env:
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_PRICING_CALCULATOR_CREDENTIALS }}
        run: |
          echo "$GCP_SERVICE_ACCOUNT_KEY" > test-key.json
          echo "Service account key saved to test-key.json"
          ls -l test-key.json
